src/accounts/urls.py
from accounts.views import AccountLoginView, AccountLogoutView, AccountPwdChangeView, \
    AccountRegistrationView, AccountUpdateView, LeaderboardView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPwdChangeView.as_view(), name='password'),
    path('leaderboard/', LeaderboardView.as_view(), name='rating'),
]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultCreateView, TestResultQuestionView, \
    TestResultDetailsView, TestResultUpdateView, TestResultDeleteView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('<uuid:uuid>/results/create/', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next/', TestResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details/', TestResultDetailsView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update/', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete/', TestResultDeleteView.as_view(), name='result_delete'),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    rating = models.IntegerField(default=0)

src/quiz/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import User
from core.models import BaseModel
from core.utils import generate_uuid


class Test(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    # topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def __str__(self):
        return f'{self.title}'

    def questions_count(self):
        return self.questions.count()

    def get_best_result(self):
        max_correct_answers = self.results.order_by('-num_correct_answers').first().num_correct_answers
        return max_correct_answers

    def get_best_user(self):
        bu = self.results.order_by('-num_correct_answers').first().user
        return bu

    def get_last_run(self):
        last_run = self.results.order_by('-write_date').first().write_date
        return last_run


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.text}'


class Choice(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    user = models.ForeignKey(to=User, related_name='results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    current_order_number = models.PositiveSmallIntegerField(null=True)

    num_correct_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )
    num_incorrect_answers = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(Test.QUESTION_MAX_LIMIT)
        ]
    )

    def update_result(self, order_number, question, selected_choices):
        correct_choices = [
            choice.is_correct
            for choice in question.choices.all()
        ]

        correct_answer = True
        for z in zip(correct_choices, selected_choices):
            correct_answer &= (z[0] == z[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number
        if order_number == question.test.questions_count():
            self.state = self.STATE.FINISHED
            self.user.rating += self.get_points()
        self.user.save()
        self.save()

    def get_time_spent(self):
        return self.write_date - self.create_date

    def get_success_rate(self):
        return self.num_correct_answers / self.test.questions_count() * 100

    def get_points(self):
        points = self.num_correct_answers - self.num_incorrect_answers
        # max(0, self.num_correct_answers - self.num_incorrect_answers)
        return 0 if points < 0 else points

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import User


class AccountRegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = User
        fields = [
            'username', 'first_name', 'last_name', 'email',
            'bio', 'location', 'birth_date', 'image'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get('password')
        if password:
            password.help_text = password.help_text.replace(
                '../password/', './password')

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm
from accounts.models import User
from quiz.models import Result, Test


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'User {self.request.POST["username"]} has successfully created')
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'User {self.request.user} has successfully logged in')
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        messages.success(self.request, f'User {self.request.user} has logged out')
        return super().dispatch(request, *args, **kwargs)


class AccountUpdateView(UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('index')
    form_class = AccountUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'Account of user {self.request.user} has been successfully updated')
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        # context['result_list'] = self.get_queryset()
        return context

    def get_queryset(self):
        return self.object.results.all().order_by('state')


class AccountPwdChangeView(PasswordChangeView):
    model = User
    template_name = 'password.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self):
        return self.request.user


class LeaderboardView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'leaderboard.html'
    context_object_name = 'users'
    queryset = User.objects.filter(rating__gt=0).order_by('-rating')

src/accounts/templates/leaderboard.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <h1>Leaderboard</h1>
{% endblock %}

{% block content %}

<table class="table table-hover">
      <tr>
        <th>#</th>
        <th></th>
        <th>Full name</th>
        <th>Rating</th>
      </tr>

        {% for user in users %}

              <tr>
                <td>{{ forloop.counter }}</td>
                <td><img class="rounded-circle p-1 m-1" width="80" height="80"  src="{{ user.image.url }}"></td>
                <td>{{ user.get_full_name }}</td>
                <td>{{ user.rating }}</td>
              </tr>
        {% endfor %}

</table>


{% endblock %}

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Log in as a user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <div class="mt-3">
            <input class="btn btn-success" type="submit" value="Log in">
            <a class="btn btn-light" href="{% url 'index' %}">Home</a>
        </div>
    </form>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block action %}
<h2>Logout page</h2>
{% endblock %}

{% block main %}
<!--<form method='post'>-->
<!--     {% csrf_token %}-->
<!--     {{ form|crispy }}-->
<!--      <input type="submit" value="Login">-->

<!--</form>-->
<!--    <a class="btn btn-light" href="{% url 'index' %}">Home</a>-->
{% endblock %}

src/accounts/templates/password.html
{% extends 'base.html' %}

{% block action %}
    <h2>Password change</h2>
{% endblock %}

{% block main %}
{% load crispy_forms_tags %}
<form method='post'>
     {% csrf_token %}
     {{ form|crispy }}
      <input type="submit" value="Save">

</form>

{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block action %}
<h2>Account update</h2>
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
    <div class="media">
        <div class="img-circle.vert">
            <img class="rounded-circle p-1 m-1" width="200" height="200" src="{{ user.image.url }}">
        </div>
        <div class="media-body p-3 m-3">
            <h2 class="account-heading">{{ user.username }}</h2>
            <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>

     {{ form|crispy }}

     <input type="submit" value="Save">
</form>
<br>
<table class="table table-striped table-hover">
      <tr>
        <th>#</th>
        <th>Create date</th>
        <th>Write date</th>
        <th>Test</th>
        <th>Points</th>
        <th>State</th>
        <th>Actions</th>
      </tr>
        {% for result in object_list %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ result.create_date }}</td>
                <td>{{ result.write_date }}</td>
                <td>{{ result.test }}</td>
                <td>{{ result.get_points }}</td>
                <td>{{ result.get_state_display }}</td>
                <td>
                    {% if result.state == result.STATE.NEW %}
                        <a href="{% url 'tests:result_update' result.test.uuid result.uuid %}" class="btn-lg btn-warning">CONTINUE</a>
                        <a href="{% url 'tests:result_delete' result.test.uuid result.uuid %}" class="btn-lg btn-danger">DELETE</a>
                    {% else %}
                        <a href="{% url 'tests:result_delete' result.test.uuid result.uuid %}" class="btn-lg btn-danger">DELETE</a>
                    {% endif %}
                </td>
              </tr>
        {% endfor %}
        </table>

{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block header %}
        <h1>Register new user</h1>
{% endblock %}

{% block content %}
    <form method="post">

        {% csrf_token %}

        {{form|crispy}}

        <input class="btn btn-success" type="submit" value="Register">
        <a class="btn btn-light" href="{% url 'index' %}">Home</a>
    </form>
{% endblock %}