src/accounts/urls.py
from accounts.views import AccountLoginView, AccountLogoutView, AccountPwdChangeView, \
    AccountRegistrationView, AccountUpdateView, LeaderboardView

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPwdChangeView.as_view(), name='password'),
    path('leaderboard/', LeaderboardView.as_view(), name='rating'),
]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('quizes/', include('quiz.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path

from quiz.views import TestDetailView, TestListView, TestResultCreateView, TestResultQuestionView, \
    TestResultDetailsView, TestResultUpdateView, TestResultDeleteView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<uuid:uuid>/', TestDetailView.as_view(), name='details'),
    path('<uuid:uuid>/results/create/', TestResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/questions/next/', TestResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/details/', TestResultDetailsView.as_view(), name='result_details'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/update/', TestResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/results/<uuid:result_uuid>/delete/', TestResultDeleteView.as_view(), name='result_delete'),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Quiz</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Main</a>
    <a class="navbar-brand" href="{% url 'tests:list' %}">Tests</a>
    <a class="navbar-brand" href="{% url 'accounts:rating' %}">Leaderboard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                 <li>
                     <img src="{{user.image.url}}" class="rounded mx-auto d-block" width="40" height="40">
                 </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                 </li>
            {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:registration' %}">Registration</a>
                 </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                 </li>
            {% endif %}
        </ul>
    </div>
  </div>
</nav>


<div class="container">

        {% include 'includes/messages.html' %}

        <div class="border rounded text-center p-3 m-3 mb-5 shadow">
            {% block header %}
                <h1>
                    Welcome to Quiz!!!
                </h1>
            {% endblock %}
        </div>

        {% block content %}
        {% endblock %}
  </div>


</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block action %}
    <h2>Welcome to Quiz</h2>
{% endblock %}

{% block main %}
{% endblock %}